### ISSUE TITLE
Zephyr Website navigation links offset

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#150]
Some navigation links jumps past the relevant headline to areas further down the page.

It has been suggested that this can be addressed by adding spacing in the formatting and/or by inserting specific targets.

**Comment by dbkinder** [comment]
Specifically, links to targets within a page (such as https://dev-zephyr-mcg.pantheonsite.io/community/#blog) are displayed with the target behind the page header:

![image](https://user-images.githubusercontent.com/11063618/69579946-5f79ad00-0f88-11ea-86b6-93005b92b6ae.png)

instead of having the link target location visible:

![image](https://user-images.githubusercontent.com/11063618/69579979-73251380-0f88-11ea-853e-506b30fae497.png)
