### ISSUE TITLE
Zephyr Website: Update developer resource page with 2.1 release info

### ISSUE THREAD

**Issue by mimeriza** [zephyrproject-rtos/infrastructure-old#193]
Currently shows September but obviously that's not right. Update per TSC.

**Comment by dbkinder** [comment]
Not sure what the problem is here.  Zephyr 2.0 release WAS released in September 2019.  We're about to release 2.1 (in December 2019).

**Comment by mimeriza** [comment]
My bad. I misunderstood what Kate was saying. The 2.1 release is what needs to be updated on the website.

**Comment by dbkinder** [comment]
https://dev-zephyr-mcg.pantheonsite.io/developer-resources/#current-release needs to be updated with 2.1 info (release happened Dec 8).  Also, we need to keep the 1.14 release info there since that's an LTS release.

We are excited to announce the release of Zephyr RTOS version 2.1.0!

Major enhancements with this release include (but are not limited to):

•	Normalized APIs across all architectures.
•	Expanded support for ARMv6-M architecture.
•	Added support for numerous new boards and shields.
•	Added numerous new drivers and sensors.
•	Added new TCP stack implementation (experimental).
•	Added BLE support on Vega platform (experimental).
•	Memory size improvements to Bluetooth host stack.

The detailed release notes can be found here:
https://github.com/zephyrproject-rtos/zephyr/releases/tag/zephyr-v2.1.0

**Comment by Lloveday** [comment]
complete

**Comment by mimeriza** [comment]
Verified.
